/**
 * AI Stub Functions - Placeholder implementations
 * These return mock data without calling any external AI services
 */

export interface AIAnalysisResult {
  autoCategory: string
  autoTitle: string
  autoDescription: string
  suggestedPrice: number
  suggestedAuctionPrice: number
  suggestedShipping: number
  detectedBrand?: string
  detectedModel?: string
  itemSpecifics?: Record<string, any>
  confidenceScore?: number
  message: string
}

/**
 * Analyze images and return stub AI data
 * @param imagePaths - Array of image file paths (not used in stub)
 * @param listingId - Optional listing ID (not used in stub)
 */
export async function analyzeImagesStub(
  imagePaths: string[],
  listingId?: string | number
): Promise<AIAnalysisResult> {
  // Simulate processing delay
  await new Promise(resolve => setTimeout(resolve, 500))

  return {
    autoCategory: 'Electronics (stub)',
    autoTitle: 'AI Placeholder Title - Product Listing',
    autoDescription: 'This is a placeholder description generated by the AI stub. The actual AI service is not connected yet. This product appears to be in good condition and ready for listing.',
    suggestedPrice: 49.99,
    suggestedAuctionPrice: 29.99,
    suggestedShipping: 12.99,
    detectedBrand: 'Generic Brand (stub)',
    detectedModel: 'Model XYZ (stub)',
    itemSpecifics: {
      condition: 'Used',
      color: 'Black',
      material: 'Plastic/Metal',
      features: ['Feature 1', 'Feature 2']
    },
    confidenceScore: 0.75,
    message: 'AI not connected yet — using placeholder data.'
  }
}

/**
 * Generate title from images (stub)
 */
export async function generateTitleFromImagesStub(
  imagePaths: string[],
  listingId?: string | number
): Promise<{ title: string }> {
  await new Promise(resolve => setTimeout(resolve, 300))
  
  return {
    title: 'Product Listing - AI Not Connected'
  }
}

/**
 * Generate description from product info (stub)
 */
export async function generateDescriptionStub(productInfo: {
  brand?: string
  model?: string
  condition?: string
  itemSpecifics?: Record<string, any>
}): Promise<{ description: string }> {
  await new Promise(resolve => setTimeout(resolve, 300))
  
  const conditionText = productInfo.condition || 'Used'
  const brand = productInfo.brand || 'Product'
  
  return {
    description: `This ${brand} item is in ${conditionText} condition. This is a placeholder description generated by the AI stub.`
  }
}

/**
 * Generate pricing suggestions (stub)
 */
export async function generatePricingStub(listing: any): Promise<{
  suggestedPrice: number
  suggestedAuctionPrice: number
  suggestedShipping: number
}> {
  await new Promise(resolve => setTimeout(resolve, 200))
  
  return {
    suggestedPrice: 49.99,
    suggestedAuctionPrice: 29.99,
    suggestedShipping: 12.99
  }
}

/**
 * Create draft listing structure (stub - not uploaded to eBay)
 */
export function createDraftListingStub(listing: any): {
  status: string
  title: string
  category: string
  description: string
  price: number
  images: string[]
  message: string
} {
  return {
    status: 'draft_stub',
    title: listing.title || listing.aiAnalysis?.autoTitle || 'AI Placeholder Title',
    category: listing.category?.name || listing.aiAnalysis?.autoCategory || 'Electronics (stubbed)',
    description: listing.description || listing.aiAnalysis?.autoDescription || 'Placeholder description',
    price: Number(listing.suggestedPrice) || 49.99,
    images: listing.images?.map((img: any) => img.url) || [],
    message: 'Draft listing generated locally. eBay API not connected yet.'
  }
}


