/**
 * AI Analysis Stub - Placeholder system
 * Returns hardcoded data without calling external APIs
 * This allows full workflow testing before real AI integration
 */

/**
 * Analyze images using stub function (no real AI)
 * @param {string[]} imagePaths - Array of image file paths
 * @returns {Promise<Object>} Stub analysis results
 */
export async function analyzeImagesStub(imagePaths) {
    // Simulate processing delay
    await new Promise(resolve => setTimeout(resolve, 1000));

    // Return hardcoded placeholder data
    return {
        title: "AI-Generated Title (Placeholder)",
        description: "This is a placeholder description generated by the AI stub. The real AI analysis will provide detailed product information, features, and specifications when connected.",
        brand: "Generic Brand (Stub)",
        model: "Model XYZ-123 (Stub)",
        category: "Electronics > Consumer Electronics (Stubbed)",
        itemSpecifics: JSON.stringify({
            color: "Black",
            material: "Plastic/Metal",
            size: "Standard",
            features: ["Feature 1 (Placeholder)", "Feature 2 (Placeholder)", "Feature 3 (Placeholder)"],
            condition: "Used - Good"
        }),
        confidenceScore: 0.75,
        keywords: ["placeholder", "ai", "stub", "electronics", "product"],
        condition: "good",
        analyzedAt: new Date(),
        message: "AI analysis not connected yet — this is dummy data."
    };
}

/**
 * Generate enhanced description using stub (no real AI)
 * @param {Object} productInfo - Product information
 * @returns {Promise<string>} Stub description
 */
export async function generateDescriptionStub(productInfo) {
    await new Promise(resolve => setTimeout(resolve, 500));
    
    return `This is a placeholder product description generated by the AI stub system.

Product Details:
- Title: ${productInfo.title || 'Unknown Product'}
- Brand: ${productInfo.brand || 'N/A'}
- Model: ${productInfo.model || 'N/A'}
- Condition: ${productInfo.condition || 'N/A'}

When the real AI is connected, this will be replaced with a compelling, detailed description that highlights key features and benefits.

[AI Placeholder - Real AI Not Connected Yet]`;
}

/**
 * Generate pricing suggestions using stub (no real AI)
 * @param {Object} listing - Listing information
 * @returns {Promise<Object>} Stub pricing data
 */
export async function generatePricingStub(listing) {
    await new Promise(resolve => setTimeout(resolve, 800));
    
    return {
        suggestedPrice: 49.99,
        auctionStartPrice: 29.99,
        suggestedShipping: 12.99,
        confidence: 0.75,
        marketData: {
            soldListings: {
                count: 5,
                avgPrice: 52.50,
                medianPrice: 49.99,
                range: { min: 35.00, max: 75.00 }
            },
            activeListings: {
                count: 8,
                avgPrice: 55.25,
                medianPrice: 52.00,
                range: { min: 40.00, max: 80.00 }
            }
        },
        conditionMultiplier: 0.70,
        markdownSuggestion: null,
        analyzedAt: new Date(),
        message: "Pricing suggestions are placeholder data. Real market analysis will be available when AI is connected."
    };
}

export default {
    analyzeImagesStub,
    generateDescriptionStub,
    generatePricingStub
};

